config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :goals, only: [:index]
  resources :github_goals
  resources :users, only: [:edit, :update]


  namespace 'api' do
    namespace 'v1' do
      resources :github_goals, only: [:index, :show]
      resources :fitbit_goals, only: [:index, :show]
      resources :users, only: [:index, :show]
    end
  end


  get '/login'     => redirect('/auth/twitter'), as: :login
  get '/goodreads' => redirect('/auth/goodreads'), as: :new_goodread
  get '/fitbit' => redirect('/auth/fitbit'), as: :fitbit
  get '/github' => redirect('/auth/github'), as: :github
  get '/auth/goodreads/callback', to: 'goodreads#create'
  get '/auth/github/callback', to:'githubs#create'
  get '/logout' => 'sessions#destroy', as: :logout
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  get '/auth/fitbit/callback', to: 'fitbit#create'

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    if !current_user.github_goals.empty?
      @current_github_goal = current_user.github_goals.last.commit_goal
      @todays_commits = current_user.github_goals.last.daily_commit_count
      @current_streak = current_user.github_goals.last.streak
      @longest_streak = current_user.github_goals.last.longest_streak
      @daily_progress = current_user.github_goals.last.progress
      if current_user.github_token?
        GithubWorker.perform_async(current_user.id)
      end
    end

      @github_goal = GithubGoal.find_by(user_id: current_user.id)

      @first_name = current_user.first_name
      @twitter_pic = current_user.high_res_profile
      @fitbit = current_user.oauth_accounts.select do |account|
        account.provider == 'fitbit'
    end

    if current_user.fitbit_goal
      @fitbit_steps    = current_user.fitbit_goal.daily_steps_goal
      @todays_steps    = current_user.fitbit_goal.todays_steps
      @todays_distance = current_user.fitbit_goal.todays_distance
      @progress        = current_user.fitbit_goal.progress
    end

    if current_user.goodreads_uid
      @current_books = GoodreadsApi.get_current_books(current_user)
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/index.html.erb
<div id="background">
  <div id="sidebar">
    <img src='<%= @twitter_pic %>' alt="Twitter Profile Pic" class="profile_pic">
    <h5><%= @first_name %></h5>

    <% if current_user.github_goals.count == 0 %>
      <%= link_to 'GitHub Integration', github_path, class: 'button' %>
    <% end %>
    <% if @fitbit.count < 1 %>
      <%= link_to 'FitBit Integration', fitbit_path, class: 'button' %>
    <% end %>
    <%= link_to 'GoodReads Int.', new_goodread_path, class: 'button' %>
    <%= link_to 'Text Reminders', edit_user_path(current_user), class: 'button' %>

  </div>


  <div class="row">
    <div class="medium-3 columns"></div>
    <div class="medium-9 large-9 columns panel radius github">
      <img src='/assets/github.png' alt="GitHub" id="mini_logo">
      <h5>Daily commit goal: <%= @current_github_goal %></h5>
      <h5>Commits today: <%= @todays_commits %></h5>
      <h5>Progress: </h5>
      <% if current_user.github_goals.count > 0 %>
        <div class="progress success radius round">
          <span class="meter" style="width: <%= @daily_progress %>%"><%= @daily_progress.to_i %>%</span>
        </div>
      <% end %>
      <h5>Current Streak:  <%= @current_streak %> | Longest Streak: <%= @longest_streak %> </h5>
    </div>
  </div>


  <div class="row">
    <div class="medium-3 columns"></div>
    <div class="medium-9 large-9 columns panel radius fitbit-panel">
      <img src='/assets/fitbit.png' alt="FitBit" id="mini_logo">
      <div id="coming_soon">Steps Goal:<%= @fitbit_steps %></div>
      <div>Today's Steps:<%= @todays_steps %></div>
      <div>Today's Distance:<%= @todays_distance  %></div>
      <% if current_user.fitbit_goal %>
        <div class="progress alert">
          <span class="meter" style="width: <%= @progress %>%"><%= @progress%>%</span>
        </div>
      <% end %>
    </div>
  </div>


  <div class="row">
    <div class="medium-4 columns"></div>
    <div class="medium-8 columns panel radius fitbit-panel">
      <img src='/assets/good_reads.png' alt="GoodReads" id="mini_logo">
      <div>
        <% if current_user.goodreads_uid %>
        <button href="#" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="button dropdown">Current Books</button><br>
          <ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true" tabindex="-1">
            <% @current_books.each do |book| %>
              <li id="<%=book%>"><a href="#"><%= book %></a></li>
            <% end %>
          </ul>
        <% end %>
    </div>
  </div>



</div>