config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :goals, only: [:index]
  resources :github_goals
  resources :users, only: [:edit, :update]


  namespace 'api' do
    namespace 'v1' do
      resources :github_goals, only: [:index, :show]
      resources :fitbit_goals, only: [:index, :show]
      resources :users, only: [:index, :show]
    end
  end


  get '/login'     => redirect('/auth/twitter'), as: :login
  get '/goodreads' => redirect('/auth/goodreads'), as: :new_goodread
  get '/fitbit' => redirect('/auth/fitbit'), as: :fitbit
  get '/github' => redirect('/auth/github'), as: :github
  get '/auth/goodreads/callback', to: 'goodreads#create'
  get '/auth/github/callback', to:'githubs#create'
  get '/logout' => 'sessions#destroy', as: :logout
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  get '/auth/fitbit/callback', to: 'fitbit#create'

end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% if flash.notice %>
    <div data-alert class="alert-box success">
      <%= notice %>
      <a href="#" class="close">&times;</a>
    </div>
  <% elsif flash[:error] %>
    <div data-alert class="alert-box failure">
      <%= flash[:error] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% elsif flash[:log_out]  %>
    <div data-alert class="alert-box warning">
      <%= flash[:log_out] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<!-- <div class="sticky"> -->
  <nav class='top-bar top_bar_color' data-topbar role='navigation'>
    <ul class='title-area'>
      <li class='name'>
        <h1><%= link_to 'Successive Life', root_path %></h1>
      </li>
    </ul>

    <section class='top-bar-section'>
      <ul class='right'>
        <% if current_user %>
          <li><%= link_to 'Log Out', logout_path %>
          <li class="has-dropdown"><%= link_to 'My Goals', goals_path %>
            <% if current_user.github_goals.count >= 1 %>
              <ul class="dropdown">
                <li><%= link_to 'GitHub Settings', edit_github_goal_path(current_user.github_goals.first) %></li>
                <li><%= link_to 'FitBit Settings', '#' %></li>
              </ul>
            <% end %>
          </li>
        <% else %>
          <li><%= link_to 'Log In', login_path %>
        <% end %>
      </ul>
    </section>
  </nav>
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Successive Life" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href="//vjs.zencdn.net/4.10.0/video-js.css" rel="stylesheet">
    <script src="//vjs.zencdn.net/4.10.0/video.js"></script>
  </head>


  <body>
    <%= render partial: 'layouts/navbar', :locals => { :github_goal => @github_goal } %>
    <%= render "layouts/flash" %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>